spring:
  datasource:
    url: jdbc:mysql://bj-cdb-ej9icuug.sql.tencentcdb.com:25161/tinyurl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: testpaper
    password: qxl110220330.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 111.229.130.92
      port: 6543
      password: abcd1234
      database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      connection-timeout: 20000
#      max-lifetime: 1800000
tinyurl:
  prefix: https://api.testpaper.fun/
  expireSeconds: 604800